#%RAML 1.0 NamedExample
  - ID: "12"
    brand: "Audi"
    model: "A1"
    year: 2017
    price: 12500
    transmission: "Manual"
    mileage: "15679"
    fuelType: "Diesel"
    tax: 267
    mpg: 56
    engineSize: 2
  - ID: "67"
    brand: "BMW"
    model: "7 series"
    year: 2017
    price: 15000
    transmission: "Automatic"
    mileage: "15676"
    fuelType: "Petrol"
    tax: 269
    mpg: 59
    engineSize: 4