#%RAML 1.0 NamedExample
status: "ERROR"
correlationId: "1234-5678-9764"
applicationName: "ABC"
errorCode: "500"
errorCategory: "HTTP"
errorType: "Internal Server Error"
errorMessage: "Server not found"